name: Moodle Plugin CI

########################################################################################################################

on: [ push, pull_request ]

########################################################################################################################

jobs:
  call-moodle-ci-workflow:
    uses: Opencast-Moodle/moodle-workflows-opencast/.github/workflows/moodle-ci.yml@main